import Link from 'next/link';
import {notFound} from 'next/navigation';

const projects={
  'mera-markaz':{title:'Mera Markaz',type:'Android finance & utility suite',image:'/projects/mera-markaz-thumbnail.png',intro:'Money, bills and everyday services—designed around life in Pakistan.',body:'Mera Markaz combines expense tracking, recurring bills, fuel insights, secure cloud backup and an optional Gemini-powered financial assistant. The experience supports English and Urdu, persistent guest sessions, Google, Facebook and email sign-in, plus encrypted user data.',features:['Bilingual English and Urdu experience','Offline-first local finance records','Encrypted account backup and restore','Optional, consent-based Markaz AI','Bills, fuel, expenses and useful calculators'],stack:'Flutter · Firebase · SQLCipher · Gemini'},
  'testmind-ai':{title:'TestMind AI',type:'AI-assisted quality engineering',image:'/projects/testmind-dashboard.png',intro:'Turn product context into test coverage that teams can understand and use.',body:'TestMind AI converts user stories, product descriptions, telemetry and screen recordings into structured test cases. Teams can manage execution, produce Playwright, Cypress and Selenium starters, track defects and publish QA assets directly to GitHub.',features:['AI test generation from requirements','Multimodal screen-recording analysis','Test execution and bug tracking','Automation starter generation','GitHub repositories, issues and pull requests'],stack:'React · TypeScript · Node.js · PostgreSQL · Gemini · Groq'},
  simplepos:{title:'SimplePOS',type:'Offline-first desktop point of sale',image:'/projects/simplepos-hero.png',intro:'Fast retail operations that keep working—even when the connection does not.',body:'SimplePOS is a Windows desktop point-of-sale application for modern multi-store businesses. Checkout writes locally first, while optional cloud synchronization keeps shared catalog, customer, supplier and reporting data available across stores.',features:['Offline-first checkout with SQLite','Multi-store inventory and permissions','Customers, suppliers and purchase orders','Optional PostgreSQL cloud synchronization','Dedicated Windows desktop installer'],stack:'Electron · React · Node.js · SQLite · PostgreSQL'},
} as const;

export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects[slug as keyof typeof projects];if(!p)notFound();return <main className="detail-page"><nav className="nav shell"><Link className="brand" href="/"><span className="brand-mark">L</span><span>Logivyre Labs</span></Link><Link className="nav-cta" href="/">All projects</Link></nav><header className="detail-hero shell"><p className="section-index">{p.type}</p><h1>{p.title}</h1><p>{p.intro}</p></header><section className="detail-image shell"><img src={p.image} alt={`${p.title} interface`}/></section><section className="detail-body shell"><div><p className="section-index">THE PRODUCT</p><h2>Built to make demanding work feel straightforward.</h2></div><div><p>{p.body}</p><ul>{p.features.map(f=><li key={f}>{f}</li>)}</ul><p className="stack-label">Technology</p><p>{p.stack}</p>{slug==='simplepos'&&<Link className="button primary" href="/releases">Download for Windows</Link>}</div></section><footer><div className="shell footer-bottom"><span>© 2026 Logivyre Labs</span><Link href="/">Back to portfolio</Link></div></footer></main>}
