import Link from 'next/link';

const products = [
  { id:'mera-markaz', eyebrow:'Personal finance · Android', title:'Mera Markaz', description:'A bilingual finance and utility companion built for Pakistan—expenses, bills, fuel, encrypted backup and practical AI guidance in one calm place.', image:'/projects/mera-markaz-thumbnail.png', accent:'mint', tags:['Flutter','Firebase','Gemini','Urdu'] },
  { id:'testmind-ai', eyebrow:'Quality engineering · Web', title:'TestMind AI', description:'An AI-assisted quality engineering workspace that turns requirements, telemetry and screen recordings into structured test coverage and automation starters.', image:'/projects/testmind-dashboard.png', accent:'violet', tags:['React','Node.js','Gemini','GitHub'] },
  { id:'simplepos', eyebrow:'Retail operations · Windows', title:'SimplePOS', description:'An offline-first desktop point-of-sale system with multi-store inventory, checkout, customer balances and optional cloud synchronization.', image:'/projects/simplepos-hero.png', accent:'amber', tags:['Electron','React','SQLite','Node.js'] },
];

function Arrow(){return <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M5 12h14M13 6l6 6-6 6"/></svg>}

export default function Home(){return <main>
  <nav className="nav shell" aria-label="Main navigation"><Link className="brand" href="/"><span className="brand-mark">L</span><span>Logivyre Labs</span></Link><div className="nav-links"><a href="#work">Projects</a><a href="#about">Studio</a><a href="#contact">Contact</a><Link className="nav-cta" href="/releases">Downloads</Link></div></nav>
  <section className="hero shell"><div className="hero-copy"><p className="kicker"><span/> Independent product studio</p><h1>Useful software,<br/><em>thoughtfully engineered.</em></h1><p className="hero-lede">Logivyre Labs designs focused digital products for everyday finance, quality engineering and modern retail operations.</p><div className="hero-actions"><a className="button primary" href="#work">Explore our work <Arrow/></a><a className="text-link" href="#about">Meet the studio <Arrow/></a></div></div><div className="hero-system"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core"><span>L</span><small>LOGIVYRE</small></div><div className="satellite s-one"><img src="/projects/mera-markaz-logo.png" alt=""/><span>Finance</span></div><div className="satellite s-two"><img src="/projects/testmind-logo.png" alt=""/><span>Quality</span></div><div className="satellite s-three"><img src="/projects/simplepos-icon.png" alt=""/><span>Retail</span></div></div></section>
  <section className="work shell" id="work"><div className="section-heading"><div><p className="section-index">01 / SELECTED WORK</p><h2>Products built around<br/>real-world problems.</h2></div><p>Three distinct products. One principle: make complex work feel clear, dependable and human.</p></div><div className="project-grid">{products.map((p,i)=><article className={`project-card ${p.accent}`} key={p.id}><Link href={`/projects/${p.id}`} className="project-visual"><span className="project-number">0{i+1}</span><img src={p.image} alt={`${p.title} product preview`}/></Link><div className="project-copy"><p className="eyebrow">{p.eyebrow}</p><h3>{p.title}</h3><p>{p.description}</p><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><Link className="project-link" href={`/projects/${p.id}`}>View project <Arrow/></Link></div></article>)}</div></section>
  <section className="studio" id="about"><div className="shell studio-grid"><p className="section-index">02 / THE STUDIO</p><div><h2>Technology should remove friction—not create more of it.</h2><p>Logivyre Labs is an independent software studio creating secure, practical products across mobile, web and desktop. We care about quiet interfaces, resilient systems and details that hold up after launch.</p></div><div className="principles"><div><strong>01</strong><span>Useful by design</span></div><div><strong>02</strong><span>Private by default</span></div><div><strong>03</strong><span>Built to evolve</span></div></div></div></section>
  <section className="download-callout shell"><div><p className="section-index">WINDOWS RELEASES</p><h2>Try our desktop software.</h2><p>Download verified Windows installers and view release information from one place.</p></div><Link className="button light" href="/releases">Browse downloads <Arrow/></Link></section>
  <footer id="contact"><div className="shell footer-grid"><div><Link className="brand inverse" href="/"><span className="brand-mark">L</span><span>Logivyre Labs</span></Link><p>Independent software studio.<br/>Building from Pakistan for everywhere.</p></div><div><span>Navigate</span><a href="#work">Projects</a><a href="#about">Studio</a><Link href="/releases">Downloads</Link></div><div><span>Contact</span><a href="mailto:hello@logivyrelabs.com">hello@logivyrelabs.com</a><p>Pakistan · Remote</p></div></div><div className="shell footer-bottom"><span>© 2026 Logivyre Labs</span><span>Build useful things.</span></div></footer>
</main>}
